### ISSUE TITLE
Status of the crate?

### ISSUE THREAD

**Issue by ijager** [lucazulian/vl6180x#1]
Hi @lucazulian, 

I was working on my [own vl6180x driver](https://github.com/devboard-io/vl6180x-rs) when I encountered this one. I saw you already claimed the name on crates.io. Are you planning on working on this driver again? Perhaps we can combine efforts. It would be a waste to have multiple similar crates.

**Comment by lucazulian** [comment]
Hi @ijager absolutely! If you wanna merge into this repo with a PR I will accept any kind of contribution!

**Comment by ijager** [comment]
Okay I'll make a pull request!

**Comment by lucazulian** [comment]
> Okay I'll make a pull request!

Thank you so much!
